version: "3"
services:
  db:
    image: "postgres:14"
    container_name: "martenreprodb"
    environment:
        POSTGRES_USER: martenrepro
        POSTGRES_PASSWORD: password
        POSTGRES_DB: MartenRepro
    ports:
      - "5432:5432"
    volumes:
      - ".db:/var/lib/postgresql/data"
    restart: unless-stopped


volumes:
    banking_dbdata:
